version: '3'

services:
  pret:
    # Build dockerfile
    build: .
    # Restart container in case of crashes etc
    restart: always
    ports:
      - "3333:3333"
    environment:
      - APP_KEY=ppe6roFLla4X-_KwGuTKtNm_H31LdiBc
      - DRIVE_DISK=local
      - HOST=0.0.0.0
      - PORT=3333
      - NODE_ENV=production
    # Set env variables
    # environment:
    #   APP_KEY: super_strok_key_no1_quezzes_it
    #   PG_PASSWORD: example
    #   PG_USER: postgres
